=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/DTD/brand.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT brands (brand)*>
<!ELEMENT brand EMPTY>
<!ATTLIST brand
    id CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/XML/brand.xml
<!DOCTYPE brands SYSTEM "../DTD/brand.dtd">
<brands><brand id="0f9f3ba6-e7d3-4b65-a5b8-05e6ed20919b" name="Pentax" /><brand id="11253425-e3b8-4420-a921-9c9d89a665c4" name="Nikon" /><brand id="190c9cf8-63d2-49a1-9a4c-e799bd141d71" name="Polaroid" /><brand id="33167934-7ec1-42f0-a4b1-fade0ec1849d" name="Fujifilm" /><brand id="49b8d7c6-660b-43bd-92b7-71e4b0256d44" name="Leica" /><brand id="635e8633-0c1d-4c15-9304-20930256d52b" name="Olympus" /><brand id="6c721a20-0cab-4484-aac1-52b638434a5c" name="Panasonic" /><brand id="798f6123-79cb-4600-b151-38be23783e1b" name="Sealife" /><brand id="7bd1e9d2-af22-4a66-92e4-49506a1ce9d0" name="Canon" /><brand id="b3723390-54a9-40d8-bc0d-72497c6dba82" name="Hasselblad" /><brand id="f1e22ea2-b20a-4f14-95d9-2cb6d11ebb0c" name="Sony" /></brands>
