=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/DTD/capacity.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT capacitys (capacity)*>
<!ELEMENT capacity EMPTY>
<!ATTLIST capacity
    id CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/XML/capacity.xml
<!DOCTYPE capacitys SYSTEM "../DTD/capacity.dtd">
<capacitys><capacity id="0c690aba-66e3-4e5a-88d7-3be128f1ebe4" name="30GB" /><capacity id="294f4834-50be-40a8-bcd2-d380fc565a40" name="16GB" /><capacity id="2cacab6b-a4ec-4c7f-bc8c-dcd294cc2000" name="240GB" /><capacity id="326758b5-ad5f-486d-b9d0-3bd87eb6f736" name="256GB" /><capacity id="3b57189c-0cfc-44fd-bfec-81b646c8dde0" name="4GB" /><capacity id="735327f8-d4df-41e5-98d6-399bc87fd223" name="400GB" /><capacity id="73c348c4-9614-42c6-a681-03c4538bffe7" name="1TB" /><capacity id="783de906-d342-4b31-8502-b75adba7a0de" name="60GB" /><capacity id="802b960d-934b-4e1d-86ec-b15c04fc3a94" name="120GB" /><capacity id="8dc1b2b9-0f3a-4b59-a349-c7ae8c6c9b6f" name="325GB" /><capacity id="d04d9770-56eb-4b0a-84e9-8915e47ece3f" name="8GB" /><capacity id="d054efc1-7834-4625-aac4-e7b26e8069c4" name="32GB" /><capacity id="deedfda0-212f-4527-bad3-4502db7eebaf" name="768GB" /><capacity id="e020808d-2878-4e43-a82b-b073e5659842" name="128GB" /><capacity id="e5d2a1c9-9e47-4616-baaa-fe0b41045f3d" name="650GB" /><capacity id="ed2f6f16-8774-41a3-a471-c2a1e8f232a8" name="64GB" /><capacity id="ee3b6aa7-930d-47c9-bd39-85d62ea0f824" name="512GB" /><capacity id="f41b1401-4741-4630-b837-d9aacef8b45f" name="2TB" /></capacitys>
