=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/DTD/category.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT categorys (category)*>
<!ELEMENT category EMPTY>
<!ATTLIST category
    id CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== vinhdk/XML_FINDING_CAMERA/ManagerClient/web/WEB-INF/XML/category.xml
<!DOCTYPE categorys SYSTEM "../DTD/category.dtd">
<categorys><category id="0b587429-ed6b-4343-8f75-96278b1abf02" name="Compact" /><category id="0f33ea3c-1dab-4efe-b20b-81b39a52770c" name="Analog" /><category id="26c7f613-f3d3-43e8-9b40-d3429fe1cbee" name="Rangefinder" /><category id="362ac753-5229-433f-a949-352b40cb1a13" name="Mirrorless" /><category id="3ebb6a2f-6760-4794-b5ae-b0d24ea7cb69" name="DSLR" /><category id="4617e5b3-b8e2-431c-823d-5a7a4faaf7e1" name="Instant" /><category id="65f46ceb-ab38-4f9c-b717-b5e4285ac600" name="Underwater" /><category id="a98f82be-f2f9-4571-8eb0-7f198ad5e0f6" name="Full" /><category id="d1e5fa91-9625-4359-bf64-0355e9b1555b" name="Vlogging" /><category id="d2ea0793-1596-4eee-bd47-227a39dfca8c" name="Travel" /><category id="f6a8b784-dd34-4826-a11c-b17e1e5f8d9a" name="Medium" /></categorys>
